// <auto-generated />
using System;
using AutonomiaVeiculosAPI.Infra.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutonomiaVeiculosAPI.Infra.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251208185655_AdicionandoIdVehicleEmFueling")]
    partial class AdicionandoIdVehicleEmFueling
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AutonomiaVeiculosAPI.Domain.Models.FuelType", b =>
                {
                    b.Property<int>("IdFuelType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFuelType"));

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdFuelType");

                    b.ToTable("FuelTypes", (string)null);
                });

            modelBuilder.Entity("AutonomiaVeiculosAPI.Domain.Models.Fueling", b =>
                {
                    b.Property<int>("IdFueling")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFueling"));

                    b.Property<int>("CorrentKm")
                        .HasColumnType("int");

                    b.Property<DateOnly>("FuelingDate")
                        .HasColumnType("date");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IdVehicle")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("TypeFuel")
                        .HasColumnType("int");

                    b.HasKey("IdFueling");

                    b.HasIndex("IdUser");

                    b.ToTable("Fuelings", (string)null);
                });

            modelBuilder.Entity("AutonomiaVeiculosAPI.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AutonomiaVeiculosAPI.Domain.Models.Vehicle", b =>
                {
                    b.Property<int>("IdVehicle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVehicle"));

                    b.Property<int>("Autonomy")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Fabricant")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IdFuelType")
                        .HasColumnType("int");

                    b.Property<string>("VehicleModel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdVehicle");

                    b.HasIndex("IdFuelType");

                    b.ToTable("Vehicles", (string)null);
                });

            modelBuilder.Entity("AutonomiaVeiculosAPI.Domain.Models.Fueling", b =>
                {
                    b.HasOne("AutonomiaVeiculosAPI.Domain.Models.User", "User")
                        .WithMany("Fuelings")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AutonomiaVeiculosAPI.Domain.Models.Vehicle", b =>
                {
                    b.HasOne("AutonomiaVeiculosAPI.Domain.Models.FuelType", "Type")
                        .WithMany("Vehicles")
                        .HasForeignKey("IdFuelType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("AutonomiaVeiculosAPI.Domain.Models.FuelType", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("AutonomiaVeiculosAPI.Domain.Models.User", b =>
                {
                    b.Navigation("Fuelings");
                });
#pragma warning restore 612, 618
        }
    }
}
